{% set name = "django-gravatar2" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2dbb56465e395dd8b3920d4017e27a4756912cc2ad9b11ba48cf143871a80364

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - django

test:
  imports:
    - django_gravatar

about:
  home: https://pypi.org/project/jsonLookup/
  summary: django_gravatar, helper methods for interacting with gravatars outside of template code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
